<?php

namespace AppBundle\Repository;

/**
 * MagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinRepository extends \Doctrine\ORM\EntityRepository
{
}
