horaires_index:
    path:     /
    defaults: { _controller: "AppBundle:Horaires:index" }
    methods:  GET

horaires_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Horaires:show" }
    methods:  GET

horaires_new:
    path:     /new
    defaults: { _controller: "AppBundle:Horaires:new" }
    methods:  [GET, POST]

horaires_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Horaires:edit" }
    methods:  [GET, POST]

horaires_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Horaires:delete" }
    methods:  DELETE
